#!/bin/bash

# Download script for Cashare investor and borrower page media
# Generated: 2025-12-22

cd /Users/vedi/Repositories/cashare-website/cashare-fresh/static/images

# Investor-specific images
echo "Downloading investor images..."
curl -o investors/invest-banner-line.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-banner-line.svg"
curl -o investors/invest-banner-line-banner.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-banner-line-banner.svg"
curl -o investors/invest-high-returns.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-high-returns.svg"
curl -o investors/invest-portfolio.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-portfolio.svg"
curl -o investors/invest-expert.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-expert.svg"
curl -o investors/invest-secure-investment.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-secure-investment.svg"
curl -o investors/invest-products-private.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-products-private.svg"
curl -o investors/invest-products-institutional.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-products-institutional.svg"
curl -o investors/invest-products-platform.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-products-platform.svg"
curl -o investors/invest-steps-line.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-steps-line.svg"
curl -o investors/invest-steps-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-steps-line-mobile.svg"
curl -o investors/invest-simple-steps-1.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-simple-steps-1.svg"
curl -o investors/invest-simple-steps-2.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-simple-steps-2.svg"
curl -o investors/invest-simple-steps-3.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-simple-steps-3.svg"
curl -o investors/invest-current-projects-line.svg "https://www.cashare.ch/wp-content/uploads/2025/08/invest-current-projects-line.svg"
curl -o investors/invest-current-projects-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/invest-current-projects-line-mobile.svg"

# Private investor page images
echo "Downloading private investor images..."
curl -o investors/private-investor-steps-line.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-steps-line.svg"
curl -o investors/private-investor-steps-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-steps-line-mobile.svg"
curl -o investors/private-investor-simple-steps-1.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-simple-steps-1.svg"
curl -o investors/private-investor-simple-steps-2.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-simple-steps-2.svg"
curl -o investors/private-investor-simple-steps-3.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-simple-steps-3.svg"
curl -o investors/private-investor-requirements-line.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-requirements-line.svg"
curl -o investors/private-investor-requirements-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-requirements-line-mobile.svg"
curl -o investors/private-investor-requirements-1.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-requirements-1.svg"
curl -o investors/private-investor-requirements-2.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-requirements-2.svg"
curl -o investors/private-investor-requirements-3.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-requirements-3.svg"
curl -o investors/private-investor-current-projects-line.svg "https://www.cashare.ch/wp-content/uploads/2025/09/private-investor-current-projects-line.svg"
curl -o investors/our-ratings-line.svg "https://www.cashare.ch/wp-content/uploads/2025/09/our-ratings-line.svg"
curl -o investors/our-ratings-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/our-ratings-line-mobile.svg"

# Institutional investor page images
echo "Downloading institutional investor images..."
curl -o investors/institutional-investor-simple-steps-1.svg "https://www.cashare.ch/wp-content/uploads/2025/09/institutional-investor-simple-steps-1.svg"
curl -o investors/institutional-investor-simple-steps-2.svg "https://www.cashare.ch/wp-content/uploads/2025/09/institutional-investor-simple-steps-2.svg"
curl -o investors/institutional-investor-simple-steps-3.svg "https://www.cashare.ch/wp-content/uploads/2025/09/institutional-investor-simple-steps-3.svg"
curl -o investors/cashare-platform.svg "https://www.cashare.ch/wp-content/uploads/2025/09/cashare-platform.svg"
curl -o investors/investment-notes.svg "https://www.cashare.ch/wp-content/uploads/2025/09/investment-notes.svg"
curl -o investors/investment-fund.svg "https://www.cashare.ch/wp-content/uploads/2025/09/investment-fund.svg"
curl -o investors/institutional-investor-requirements-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/09/institutional-investor-requirements-line-mobile.svg"

# Borrower - Private loan page images
echo "Downloading private loan borrower images..."
curl -o borrowers/private-borrower-steps-line.png "https://www.cashare.ch/wp-content/uploads/2025/08/private-borrower-steps-line.png"
curl -o borrowers/private-borrower-steps-mobile-line.svg "https://www.cashare.ch/wp-content/uploads/2025/08/private-borrower-steps-mobile-line.svg"
curl -o borrowers/loan-fill-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/loan-fill-icon.png"
curl -o borrowers/loan-review-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/loan-review-icon.png"
curl -o borrowers/loan-disbursement-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/loan-disbursement-icon.png"
curl -o borrowers/receive-loan-vector.png "https://www.cashare.ch/wp-content/uploads/2025/07/receive-loan-vector.png"
curl -o borrowers/receive-loan-vector-mobile.png "https://www.cashare.ch/wp-content/uploads/2025/08/receive-loan-vector-mobile.png"
curl -o borrowers/loan-icon-1.png "https://www.cashare.ch/wp-content/uploads/2025/07/loan-icon-1.png"
curl -o borrowers/loan-icon-2.png "https://www.cashare.ch/wp-content/uploads/2025/07/loan-icon-2.png"
curl -o borrowers/loan-icon-3.png "https://www.cashare.ch/wp-content/uploads/2025/07/loan-icon-3.png"
curl -o borrowers/loan-icon-4.png "https://www.cashare.ch/wp-content/uploads/2025/07/loan-icon-4.png"
curl -o borrowers/loan-icon-5.png "https://www.cashare.ch/wp-content/uploads/2025/07/loan-icon-5.png"
curl -o borrowers/Pie-1.png "https://www.cashare.ch/wp-content/uploads/2024/12/Pie-1.png"
curl -o borrowers/Icon-1.png "https://www.cashare.ch/wp-content/uploads/2024/12/Icon-1.png"
curl -o borrowers/Pie-2.png "https://www.cashare.ch/wp-content/uploads/2024/12/Pie-2.png"
curl -o borrowers/Layer_1-12.png "https://www.cashare.ch/wp-content/uploads/2024/12/Layer_1-12.png"
curl -o borrowers/Layer_1-14.png "https://www.cashare.ch/wp-content/uploads/2024/12/Layer_1-14.png"
curl -o borrowers/Layer_1-15.png "https://www.cashare.ch/wp-content/uploads/2024/12/Layer_1-15.png"

# Borrower - Mortgage/Hypotheken page images
echo "Downloading mortgage borrower images..."
curl -o borrowers/hypo-products-mortgage.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-products-mortgage.png"
curl -o borrowers/hypo-products-financing.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-products-financing.png"
curl -o borrowers/hypo-products-renovation.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-products-renovation.png"
curl -o borrowers/hypo-products-sme.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-products-sme.png"
curl -o borrowers/hypo-borrower-steps-line.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-borrower-steps-line.png"
curl -o borrowers/hypo-borrower-steps-line-mobile.svg "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-borrower-steps-line-mobile.svg"
curl -o borrowers/hypo-fill-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-fill-icon.png"
curl -o borrowers/hypo-quick-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-quick-icon.png"
curl -o borrowers/hypo-contact-icon.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-contact-icon.png"
curl -o borrowers/hypo-requirements-line.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-requirements-line.png"
curl -o borrowers/hypo-requirements-line-mobile.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-requirements-line-mobile.png"
curl -o borrowers/hypo-requirement-ratio.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-requirement-ratio.png"
curl -o borrowers/hypo-requirement-burden.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-requirement-burden.png"
curl -o borrowers/hypo-requirement-mortgage.png "https://www.cashare.ch/wp-content/uploads/2025/08/hypo-requirement-mortgage.png"

# Shared/Common images (logos, partners, etc.)
echo "Downloading shared images..."
curl -o logos/cashare-main-logo.svg "https://www.cashare.ch/wp-content/uploads/2024/12/cashare-main-logo.svg"
curl -o logos/cashare-main-logo.png "https://www.cashare.ch/wp-content/uploads/2024/12/cashare-main-logo.png"
curl -o partners/Frame-1000002702.png "https://www.cashare.ch/wp-content/uploads/2024/10/Frame-1000002702.png"
curl -o partners/Swiss-Finance-Logo.png "https://www.cashare.ch/wp-content/uploads/2024/10/Swiss-Finance-Logo.png"
curl -o partners/Swiss-Made-Software-Logo.png "https://www.cashare.ch/wp-content/uploads/2024/10/Swiss-Made-Software-Logo.png"
curl -o partners/logo-2.png "https://www.cashare.ch/wp-content/uploads/2024/10/logo-2.png"
curl -o partners/Frame-1000002746.png "https://www.cashare.ch/wp-content/uploads/2024/10/Frame-1000002746.png"
curl -o ui/Vector-10.png "https://www.cashare.ch/wp-content/uploads/2024/10/Vector-10.png"

# Product category images (used across pages)
echo "Downloading product category images..."
curl -o products/private-loan.png "https://www.cashare.ch/wp-content/uploads/2024/12/private-loan.png"
curl -o products/sme-loan.png "https://www.cashare.ch/wp-content/uploads/2024/12/sme-loan.png"
curl -o products/mortgage.png "https://www.cashare.ch/wp-content/uploads/2024/12/mortgage.png"
curl -o products/private-investor.png "https://www.cashare.ch/wp-content/uploads/2024/12/private-investor.png"
curl -o products/istitutional-investor.png "https://www.cashare.ch/wp-content/uploads/2024/12/istitutional-investor.png"

# About section images (navigation footer images)
curl -o about/who-we-are.png "https://www.cashare.ch/wp-content/uploads/2024/12/who-we-are.png"
curl -o about/crowd-lending.png "https://www.cashare.ch/wp-content/uploads/2024/12/crowd-lending.png"
curl -o about/statistics.png "https://www.cashare.ch/wp-content/uploads/2024/12/statistics.png"
curl -o about/jobs.png "https://www.cashare.ch/wp-content/uploads/2024/12/jobs.png"
curl -o about/partner.png "https://www.cashare.ch/wp-content/uploads/2024/12/partner.png"
curl -o press/press.png "https://www.cashare.ch/wp-content/uploads/2024/12/press.png"
curl -o blog/blog.png "https://www.cashare.ch/wp-content/uploads/2024/12/blog.png"

echo "Download complete!"
echo "Total images downloaded to:"
echo "  - /static/images/investors/"
echo "  - /static/images/borrowers/"
echo "  - /static/images/logos/"
echo "  - /static/images/partners/"
echo "  - /static/images/products/"
echo "  - /static/images/about/"
echo "  - /static/images/press/"
echo "  - /static/images/blog/"
echo "  - /static/images/ui/"
