// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_statistics from "./routes/api/statistics.ts";
import * as $en_about from "./routes/en/about.tsx";
import * as $en_apply_for_credit from "./routes/en/apply-for-credit.tsx";
import * as $en_index from "./routes/en/index.tsx";
import * as $en_invest from "./routes/en/invest.tsx";
import * as $fr_a_propos from "./routes/fr/a-propos.tsx";
import * as $fr_demander_un_credit from "./routes/fr/demander-un-credit.tsx";
import * as $fr_index from "./routes/fr/index.tsx";
import * as $fr_investir from "./routes/fr/investir.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $investieren from "./routes/investieren.tsx";
import * as $kredit_beantragen from "./routes/kredit-beantragen.tsx";
import * as $styleguide from "./routes/styleguide.tsx";
import * as $styleguide_buttons from "./routes/styleguide/buttons.tsx";
import * as $ueber_uns from "./routes/ueber-uns.tsx";
import * as $AnimatedCounter from "./islands/AnimatedCounter.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $LoanCalculator from "./islands/LoanCalculator.tsx";
import * as $ScrollReveal from "./islands/ScrollReveal.tsx";
import * as $StripeNav from "./islands/StripeNav.tsx";
import * as $calculator_HomeCalculator from "./islands/calculator/HomeCalculator.tsx";
import * as $calculator_LoanCalculator from "./islands/calculator/LoanCalculator.tsx";
import * as $calculator_SmeCalculator from "./islands/calculator/SmeCalculator.tsx";
import * as $calculator_YieldCalculator from "./islands/calculator/YieldCalculator.tsx";
import * as $charts_RatingsChart from "./islands/charts/RatingsChart.tsx";
import * as $charts_TimelineChart from "./islands/charts/TimelineChart.tsx";
import * as $charts_VolumesChart from "./islands/charts/VolumesChart.tsx";
import * as $styleguide_ActiveNavigation from "./islands/styleguide/ActiveNavigation.tsx";
import * as $styleguide_CollapsibleSection from "./islands/styleguide/CollapsibleSection.tsx";
import * as $styleguide_CopyToClipboard from "./islands/styleguide/CopyToClipboard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/statistics.ts": $api_statistics,
    "./routes/en/about.tsx": $en_about,
    "./routes/en/apply-for-credit.tsx": $en_apply_for_credit,
    "./routes/en/index.tsx": $en_index,
    "./routes/en/invest.tsx": $en_invest,
    "./routes/fr/a-propos.tsx": $fr_a_propos,
    "./routes/fr/demander-un-credit.tsx": $fr_demander_un_credit,
    "./routes/fr/index.tsx": $fr_index,
    "./routes/fr/investir.tsx": $fr_investir,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/investieren.tsx": $investieren,
    "./routes/kredit-beantragen.tsx": $kredit_beantragen,
    "./routes/styleguide.tsx": $styleguide,
    "./routes/styleguide/buttons.tsx": $styleguide_buttons,
    "./routes/ueber-uns.tsx": $ueber_uns,
  },
  islands: {
    "./islands/AnimatedCounter.tsx": $AnimatedCounter,
    "./islands/Counter.tsx": $Counter,
    "./islands/Header.tsx": $Header,
    "./islands/LoanCalculator.tsx": $LoanCalculator,
    "./islands/ScrollReveal.tsx": $ScrollReveal,
    "./islands/StripeNav.tsx": $StripeNav,
    "./islands/calculator/HomeCalculator.tsx": $calculator_HomeCalculator,
    "./islands/calculator/LoanCalculator.tsx": $calculator_LoanCalculator,
    "./islands/calculator/SmeCalculator.tsx": $calculator_SmeCalculator,
    "./islands/calculator/YieldCalculator.tsx": $calculator_YieldCalculator,
    "./islands/charts/RatingsChart.tsx": $charts_RatingsChart,
    "./islands/charts/TimelineChart.tsx": $charts_TimelineChart,
    "./islands/charts/VolumesChart.tsx": $charts_VolumesChart,
    "./islands/styleguide/ActiveNavigation.tsx": $styleguide_ActiveNavigation,
    "./islands/styleguide/CollapsibleSection.tsx":
      $styleguide_CollapsibleSection,
    "./islands/styleguide/CopyToClipboard.tsx": $styleguide_CopyToClipboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
